---
jobs:

- name: hello-job
  plan:
  - task: hello-embedded
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, embedded world!"]
